# Generated by Django 5.0.1 on 2024-02-08 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=100)),
                ('length', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='song_Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='song_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(to='playsinkapp.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song_artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song_genre'),
        ),
    ]
