# Generated by Django 4.2.6 on 2024-02-21 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playsinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.CharField(max_length=100, verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song_artist', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song_genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='song_artist',
            name='artist_name',
            field=models.CharField(max_length=100, verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='song_artist',
            name='song_name',
            field=models.CharField(max_length=100, verbose_name='song'),
        ),
    ]
