# Generated by Django 4.2.6 on 2024-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0002_alter_playlist_name_alter_playlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='pimage',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
