# Generated by Django 4.2.6 on 2024-02-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0003_song_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=1, upload_to='songs'),
            preserve_default=False,
        ),
    ]
