# Generated by Django 4.2.6 on 2024-02-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0004_song_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_artist',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song_artist',
            name='artist_name',
            field=models.CharField(max_length=100, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='song_artist',
            name='song_name',
            field=models.CharField(max_length=100, verbose_name='Song'),
        ),
    ]
