# Generated by Django 4.2.6 on 2024-02-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0005_song_artist_category_alter_song_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song', verbose_name='Song_name'),
            preserve_default=False,
        ),
    ]
