# Generated by Django 4.2.6 on 2024-02-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0006_remove_playlist_name_remove_playlist_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song', verbose_name='playlist'),
        ),
    ]
