# Generated by Django 4.2.6 on 2024-02-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0008_playlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='artist_name',
        ),
    ]
