# Generated by Django 4.2.6 on 2024-02-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0009_rename_name_playlist_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song', verbose_name='song_name'),
        ),
    ]
