# Generated by Django 4.2.6 on 2024-02-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0010_remove_playlist_artist_name_playlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='playsinkapp.song'),
        ),
    ]
