# Generated by Django 4.2.6 on 2024-02-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0011_remove_playlist_songs_playlist_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
