# Generated by Django 4.2.6 on 2024-02-29 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playsinkapp', '0013_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='uid',
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='playsinkapp.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_name'),
            preserve_default=False,
        ),
    ]
