# Generated by Django 4.2.6 on 2024-02-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0014_remove_playlist_sid_remove_playlist_uid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
