# Generated by Django 4.2.6 on 2024-03-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0016_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song', verbose_name='songs'),
        ),
    ]
