# Generated by Django 4.2.6 on 2024-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0018_user_playlist_delete_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_playlist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
