# Generated by Django 4.2.6 on 2024-03-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0019_user_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_playlist',
            name='songs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song', verbose_name='songs_name'),
        ),
    ]
