# Generated by Django 5.0.2 on 2024-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0021_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mood', max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
