# Generated by Django 5.0.2 on 2024-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0022_playlist_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.RemoveField(
            model_name='user_playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='user_playlist',
            name='songs',
            field=models.ManyToManyField(to='playsinkapp.song', verbose_name='songs_name'),
        ),
    ]
