# Generated by Django 5.0.2 on 2024-03-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0023_delete_playlist_remove_user_playlist_songs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='user_playlist',
            name='songs',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='playsinkapp.song', verbose_name='songs_name'),
            preserve_default=False,
        ),
    ]
