# Generated by Django 4.2.6 on 2024-03-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playsinkapp', '0024_remove_user_playlist_songs_user_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_playlist',
            name='name',
        ),
    ]
